FROM agrigorev/zoomcamp-model:3.8.12-slim

RUN pip install pipenv
RUN pip install waitress
RUN pip install flask
WORKDIR /app

RUN pipenv install

COPY ["Pipfile", "Pipfile.lock", "./"]

RUN pipenv install --system --deploy

COPY ["predict.py", "model1.bin", "dv.bin", "./"]

EXPOSE 9696

ENTRYPOINT ["waitress-serve", "--listen=0.0.0.0:9696", "predict:app"]